### ISSUE TITLE
Loggers??

### ISSUE THREAD

**Issue by crogonint** [theFox6/working_villages#11]
**Describe the bug**
Game won't load.

**To Reproduce**
At Startup

**Log**
ModError: Failed to load and run script from C:\Users\Frank\Downloads\Games\minetest-5.3.0-win64\bin\..\mods\working_villages\building_sign\init.lua:
...in64\bin\..\mods\working_villages\building_sign/util.lua:1: attempt to call field 'make_loggers' (a nil value)
stack traceback:
	...in64\bin\..\mods\working_villages\building_sign/util.lua:1: in main chunk
	[C]: in function 'dofile'
	...in64\bin\..\mods\working_villages\building_sign\init.lua:16: in main chunk
Check debug.txt for details.

**Desktop (please complete the following information):**
 - Minetest version: Current - new install

**Additional context**
That's a bummer.

**Comment by crogonint** [comment]
Damit!

Same thing happens if I turn off building sign:
ModError: Failed to load and run script from C:\Users\James\Downloads\Games\minetest-5.3.0-win64\bin\..\mods\working_villages\working_villagers\init.lua:
...\bin\..\mods\working_villages\working_villagers\init.lua:5: attempt to call field 'make_loggers' (a nil value)
stack traceback:
	...\bin\..\mods\working_villages\working_villagers\init.lua:5: in main chunk
Check debug.txt for details.

**Comment by crogonint** [comment]
Am I missing a pack that's necessary, or..?

**Comment by theFox6** [comment]
No, this is my fault.
I have not released a new version for a long time and the dependencies of this mod have become incompatible.
Now I have released a new version, but I cannot create a ContentDB release at the moment.
You don't have to wait until the problem with ContentDB is solved though,
you can download the latest release from [the release page of this repository](https://github.com/theFox6/working_villages/releases) and extract it into your mods folder.

**Comment by theFox6** [comment]
I was able to create a ContentDB release, please check if the bug still occurs with the latest version.

**Comment by crogonint** [comment]
Oh, I don't trust ContentDB to be up to date anyway. If it's not up to date in the Minetest GUI, I'll just use it here from the repo. Thanks for sorting it so quickly. :):

**Comment by crogonint** [comment]
Sorry I forgot to report back, that seems to have fixed the error. I accidentally closed the tabs in my broswer explaining how to get a village to generate, so I have no idea if anything actually WORKS.. but now I can start up with the mod running and it doesn't crash. :)

**Comment by theFox6** [comment]
Villages do not spawn yet, assigning jobs to villagers is fully manual at the moment.
I'm happy to hear that it is fixed though
