### ISSUE TITLE
Various deprecated warnings reported in debug.txt

### ISSUE THREAD

**Issue by revell1** [theFox6/working_villages#43]
**Describe the bug**
Various deprecated warnings reported in debug.txt when using mod in Minetest 5.7.0

These functions:
setvelocity(), getvelocity(),
setyaw(), getyaw(),
setacceleration()

**To Reproduce**
Use mod in Minetest 5.7.0, then review the debug.txt log file located in the Minetest executable directory.

**Expected behavior**
Should not be using deprecated functions, so should not get warnings.

**Screenshots**
N/A

**Log**
N/A

**Desktop (please complete the following information):**
 - Minetest version: 5.7.0
 - Other mods activated: Various

**Additional context**
N/A

**Comment by sfence** [comment]
Should be fixed in v1.5.3.
