### ISSUE TITLE
created clone on crash

### ISSUE THREAD

**Issue by lmaddox** [theFox6/working_villages#51]
I filled up my hard drive and crashed my server. Now this villager has a clone. It's certainly better than data loss.

![Screenshot_2023-12-02_21_15_32](https://github.com/theFox6/working_villages/assets/4258802/a9be65ef-68d7-404f-ba8c-f2945e959a79)

**Comment by theFox6** [comment]
Curious, but I don't think this is a working_villages issue, this may have to do with minetests way of saving the world.
